import type { WorkflowRequest } from "./types.js";

export const sampleRequests: Record<WorkflowRequest["mode"], WorkflowRequest> = {
	trend: {
		mode: "trend",
		topN: 3,
		trendSignals: [
			{
				label: "AI meal photo logging",
				targetUser: "busy health-conscious professionals",
				coreProblem: "tracking nutrition without manual entry",
				region: "us",
				chartMomentum: 82,
				categoryAcceleration: 78,
				reviewMomentum: 73,
				monetizationShift: 68,
				timeSensitivity: 64,
				distributionChange: 58,
				durability: 72,
				corroboratingSignals: ["chart uptrend", "review praise", "creator coverage"],
			},
			{
				label: "Async AI coaching for creators",
				targetUser: "solo video creators",
				coreProblem: "getting feedback without agency retainers",
				region: "global",
				chartMomentum: 67,
				categoryAcceleration: 62,
				reviewMomentum: 59,
				monetizationShift: 70,
				timeSensitivity: 55,
				distributionChange: 69,
				durability: 63,
				corroboratingSignals: ["category growth", "tool bundling"],
			},
		],
	},
	keyword: {
		mode: "keyword",
		topN: 4,
		keywordSeed: {
			seed: "habit tracker",
			targetUser: "people trying to build routines",
			coreProblem: "staying consistent after the first few days",
			region: "us",
			baseDemand: 74,
			baseCompetition: 76,
			basePainIntensity: 69,
			baseMonetizationPotential: 62,
			baseRegionalFit: 71,
			intents: ["ADHD support", "couples accountability"],
			personas: ["graduate students", "founders"],
			workflowSlices: ["night routine reset", "weekly review"],
		},
	},
	replacement: {
		mode: "replacement",
		topN: 3,
		replacementApps: [
			{
				appName: "Legacy Pantry Keeper",
				category: "inventory",
				targetUser: "families managing groceries",
				coreProblem: "tracking pantry items without tedious manual upkeep",
				region: "us",
				ongoingDemandVisibility: 66,
				reviewActivity: 58,
				updateStagnationMonths: 28,
				uxFreshness: 24,
				unresolvedComplaintIntensity: 79,
				modernAlternativeRequests: 74,
				lockInStrength: 38,
				monetizationPotential: 61,
			},
			{
				appName: "Abandoned Study Log",
				category: "education",
				targetUser: "students",
				coreProblem: "logging study sessions",
				region: "global",
				ongoingDemandVisibility: 18,
				reviewActivity: 8,
				updateStagnationMonths: 36,
				uxFreshness: 15,
				unresolvedComplaintIntensity: 40,
				modernAlternativeRequests: 20,
				lockInStrength: 15,
				monetizationPotential: 35,
			},
		],
	},
};